Vagrant.configure("2") do |config|
  config.vm.define "swarm-VGmaster-node" do |node|
      node.vm.box = "ubuntu/xenial64"
      node.vm.box_check_update = false
      node.vm.provider "virtualbox" do |vb|
        vb.name = "swarm-VBmaster-node"
        vb.memory = 1536
      end
      node.vm.hostname = "swarm-master-node"
      node.vm.network "private_network", ip: "192.168.10.2"
      node.vm.network "forwarded_port", guest: 8080, host: 3333, host_ip: "127.0.0.1"
      node.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "./hosts.txt"
        ansible.verbose = "vvv"
        ansible.playbook = "playbook1.yml"
                              end
    end


  (1.. 2 ).each do |i|
    config.vm.define "swarm-VGnode-#{i}" do |node|
      node.vm.box = "ubuntu/xenial64"
      node.vm.box_check_update = false
      node.vm.provider "virtualbox" do |vb|
        vb.name = "swarm-VBnode-#{i}"
        vb.memory = 512
      end
      node.vm.hostname = "swarm-node-#{i}"
      node.vm.network "private_network", ip: "192.168.10.#{i+2}"

    end
  end

end

